# 配置文件

# IKUUU【WEB】
# https://ikuuu.eu/auth/register?code=kYZQ
######### 多账号示例 #########
[[IKUUU]]
baseUrl = ""
name = ""
email = ""
passwd = ""

[[IKUUU]]
baseUrl = ""
name = ""
email = ""
passwd = ""
######### 多账号示例 #########

# 掘金【WEB】
# https://juejin.cn cookie
[[JUEJIN]]
cookie = ""
username = ""
password = ""

# 阿里云盘【WEB】
# https://juejin.cn refresh_token
[[ALIYUNDRIVE]]
refresh_token = ""
username = ""
password = ""

# 百度贴吧【WEB】
# http://tieba.baidu.com cookie
[[TIEBA]]
cookie = ""
