# 配置文件

# IKUUU【WEB】
# https://ikuuu.eu/auth/register?code=kYZQ
######### 多账号示例 #########
[[IKUUU]]
name = ""
email = ""
passwd = ""

[[IKUUU]]
name = ""
email = ""
passwd = ""
######### 多账号示例 #########

# 掘金【WEB】
# https://juejin.cn cookie
[[JUEJIN]]
cookie = ""
